Templates:
  AMC-Basic-Metadata:
    
    ############################################################
    # 1. IDENTITY (Who/What created the content)
    ############################################################

    # --- Author (The person) ---
    - Name: XMP-AMC:IdentityAuthorID
      Required: true
      Source:
        Type: Variable
        ValueKey: AuthorID

    - Name: XMP-AMC:IdentityAuthorAlias
      Required: true
      Source:
        Type: Variable
        ValueKey: AuthorAlias

    - Name: XMP-AMC:IdentityAuthorName
      Required: true
      Source:
        Type: Variable
        ValueKey: AuthorName

    # --- Device (The hardware) ---
    - Name: XMP-AMC:IdentityDeviceID
      Required: true
      Source:
        Type: Variable
        ValueKey: DeviceID

    - Name: XMP-AMC:IdentityDeviceAlias
      Required: true
      Source:
        Type: Variable
        ValueKey: DeviceAlias

    - Name: XMP-AMC:IdentityDeviceName
      Required: true
      Source:
        Type: Variable
        ValueKey: DeviceName

    - Name: XMP-AMC:IdentityDeviceSerialNumber
      Required: false
      Source:
        Type: Variable
        ValueKey: DeviceSerialNumber
        
    ############################################################
    # 2. ORIGIN (The immutable "backup" of the original state)
    ############################################################
    
    - Name: XMP-AMC:OriginOriginalFileName
      Required: true
      Source:
        Type: Variable
        ValueKey: OriginalFileName

    - Name: XMP-AMC:OriginOriginalDateTime
      Required: true
      Source:
        Type: Variable
        ValueKey: OriginalDateTime

    - Name: XMP-AMC:OriginOriginalSubseconds
      Required: true
      Source:
        Type: Variable
        ValueKey: OriginalSubseconds
        
    ############################################################
    # 5. STANDARD TAGS SYNC (Industry Compatibility)
    ############################################################
    
    # --- Standard Author ---
    - Name: XMP-dc:Creator
      Required: true
      Source: 
        Type: Variable
        ValueKey: AuthorName

    - Name: XMP-xmpMM:PreservedFileName
      Required: true
      Source: 
        Type: Variable
        ValueKey: OriginalFileName

  AMC-WOF-Ingest:
    
    ############################################################
    # 1. IDENTITY (Who/What created the content)
    ############################################################

    # --- Author (The person) ---
    - Name: XMP-AMC:IdentityAuthorID
      Required: true
      Source: 
        Type: Variable
        ValueKey: AuthorID 

    - Name: XMP-AMC:IdentityAuthorAlias
      Required: true
      Source: 
        Type: Variable
        ValueKey: AuthorAlias

    - Name: XMP-AMC:IdentityAuthorName
      Required: true
      Source: 
        Type: Variable
        ValueKey: AuthorName

    # --- Device (The hardware) ---
    - Name: XMP-AMC:IdentityDeviceID
      Required: true
      Source: 
        Type: Variable
        ValueKey: DeviceID

    - Name: XMP-AMC:IdentityDeviceAlias
      Required: true
      Source: 
        Type: Variable
        ValueKey: DeviceAlias

    - Name: XMP-AMC:IdentityDeviceName
      Required: true
      Source: 
        Type: Variable
        ValueKey: DeviceName
        
    ############################################################
    # 2. ORIGIN (The immutable "backup" of the original state)
    ############################################################
    
    - Name: XMP-AMC:OriginOriginalFileName
      Required: true
      Source: 
        Type: Variable
        ValueKey: OriginalFileName 

    - Name: XMP-AMC:OriginOriginalDateTime
      Required: true
      Source: 
        Type: Variable
        ValueKey: OriginalDateTime 

    - Name: XMP-AMC:OriginOriginalSubseconds
      Required: false
      Source: 
        Type: Variable
        ValueKey: OriginalSubseconds

    ############################################################
    # 3. WORKFLOW (What processing has been applied)
    ############################################################

    - Name: XMP-AMC:WorkflowIngestDerivedFileName
      Required: false
      Source: 
        Type: Variable
        ValueKey: DerivedFileName

    - Name: XMP-AMC:WorkflowIngestDerivedFolderPath
      Required: false
      Source: 
        Type: Variable
        ValueKey: DerivedFolderPath

    ############################################################
    # 4. EVENT (What the content is about)
    ############################################################
    - Name: XMP-AMC:EventName
      Required: false
      Source: 
        Type: Variable
        ValueKey: MyAlbum 
        
    ############################################################
    # 5. STANDARD TAGS SYNC (Industry Compatibility)
    ############################################################
    
    # --- Standard Author ---
    - Name: XMP-dc:Creator
      Required: true
      Source: 
        Type: Variable
        ValueKey: AuthorName

    - Name: XMP-xmpMM:PreservedFileName
      Required: true
      Source: 
        Type: Variable
        ValueKey: OriginalFileName
